version: '3.4'

services:
  radix.shop:
    image: ${DOCKER_REGISTRY-}radixshop
    container_name: radix.shop
    build:
      context: .
      dockerfile: Radix.Shop/Dockerfile
  redis:
    image: "redis:alpine"
    container_name: redis.db
    command: redis-server
    expose:
     - "6379"
    volumes:
      - redis-data:/data
      - redis-conf:/usr/local/etc/redis/redis.conf
  eventstore.db:
    image: eventstore/eventstore:20.10.2-buster-slim
    container_name: eventstore.db
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - "1113:1113"
      - "2113:2113"
    volumes:
      - type: volume
        source: eventstore-volume-data
        target: /var/lib/eventstore
      - type: volume
        source: eventstore-volume-logs
        target: /var/log/eventstore
  raven.db:
    image: ravendb/ravendb
    container_name: raven.db
    ports:
     - "8080:8080"
     - "38888:38888"
    environment:
      - RAVEN_ARGS='--Setup.Mode=None'

volumes:
  redis-data:
  redis-conf:
  eventstore-volume-data:
  eventstore-volume-logs:
