name: CD

on:
  workflow_dispatch:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PACKAGE_PUSH_TOKEN: ${{secrets.PACKAGE_PUSH_TOKEN}}
      NUGETORG_API_KEY: ${{secrets.NUGETORG_API_KEY}}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Print Env
      run: printenv
      shell: bash
    - name: BuildPackAndPush
      run: ./build.ps1
      shell: pwsh
